ARCHS?=x86_64 arm64
ARCHOPTS=$(addprefix -arch ,$(ARCHS))

FLAGS+=-mmacosx-version-min=10.9 -I$(CK_SRC_PATH) $(ARCHOPTS) -fPIC -std=c++17
LDFLAGS+=-mmacosx-version-min=10.9 -shared $(ARCHOPTS)

# Link against required frameworks
LDFLAGS+=-framework CoreFoundation

LD=clang++
CXX=clang++
